# Site settings
title: Leon & Lea
SEOTitle:  Leon & Lea
header-img: img/post-bg-Deutschland.jpg
email: 1005221070@qq.com
description: "I created this blog to write about my interests: startups and entrepreneurship, economic and politik."
keyword: "Leon, Lea, Leon & Lea, leonandlea"
url: "http://rainjwb.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/rainjwb/rainjwb.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "I’m an entrepreneur as the founder of Jiade tec Gmbh, whcih is an export and import firm."
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# SNS settings
# RSS: ture
# weibo_username:     Nibnewgnaij
# zhihu_username:     
# github_username:    
# facebook_username:  
# jianshu_username:   
# twitter_username:   
# linkedin: lrassaby


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]
gems: [jekyll-feed]
gems: [jekyll-seo-tag]
gems: [jekyll-admin]


plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-admin

  
# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# 评论系统
# Disqus（https://disqus.com/）

disqus_username: www-leonandlea-com


# Gitalk
# gitalk:
# enable: true    #是否开启Gitalk评论
# clientID: fc934c104a8dd6a69144                            #生成的clientID
# clientSecret: 0a02be1e7e0568e1bbf9456b51ab379052ed055e    #生成的clientSecret
# repo: Web-Jiang    #仓库名称
# owner: rainjwb    #github用户名
# admin: rainjwb
# distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计
# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68


# Google Analytics
ga_track_id: 'UA-124163764-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Friends
#friends: [
#    {
 #       title: "  ",
#        href: ""
 #   },{
 #       title: "简书·BY",
 #       href: "http://www.jianshu.com/u/e71990ada2fd"
 #   },{
 #       title: "Apple",
 #       href: "https://apple.com"
  #  },{
 #       title: "Apple Developer",
  #      href: "https://developer.apple.com/"
 #   }
#]